### ISSUE TITLE
Unable to install core in Raspberry Pi 3

### ISSUE THREAD

**Issue by subhasisbanik** [filecoin-station/core#286]
I am trying to install code in Raspberry Pi 3 running Node version 18.1 and NPM 8.8.0.
I tried running npm install -g @filecoin-station/core but it failed with 👍🏾 
<img width="922" alt="Screenshot 2023-12-04 at 20 24 46" src="https://github.com/filecoin-station/core/assets/25420904/8ac5c977-f748-451f-9dec-8e447912ab78">

**Comment by juliangruber** [comment]
Thank you for reporting! We can add support for 32bit arm. Do you know if the right architecture for you is arm6 or arm7?

**Comment by juliangruber** [comment]
Zinnia doesn't support arm 32bit, therefore this project unfortunately doesn't support your machine

**Comment by subhasisbanik** [comment]
Hey @juliangruber , Please find the details below:

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
