### ISSUE TITLE
Many Internal Server Error in docker log

### ISSUE THREAD

**Issue by renarios** [filecoin-station/core#388]
While running "docker logs filestation --follow" I see many internal server errors. See the attached log snippet
[filestation.log](https://github.com/filecoin-station/core/files/14803221/filestation.log)

**Comment by ricarper** [comment]
Same stituation here. 
[3/30/2024, 9:22:34 PM] INFO  Voyager exited with code: 1
[3/30/2024, 9:22:34 PM] ERROR Voyager crashed with exit code 1
[3/30/2024, 9:22:34 PM] INFO  Spark exited via signal SIGTERM
Zinnia closed all stdio with codes <SIGTERM>, 1

**Comment by ricarper** [comment]
[2024-03-31T00:23:29Z ERROR module:voyager/main] Failed to fetch content {
      cause: "All attempts to fetch content have failed. Last error: Non OK response received: 410 Gone"
    }
[2024-03-31T00:23:29Z INFO  module:voyager/main] Prod benchmark successful!
[2024-03-31T00:23:29Z ERROR module:voyager/main] Could not check if running on Saturn node { cause: `Unexpected token '<', "<!DOCTYPE "... is not valid JSON` }
[2024-03-31T00:23:29Z INFO  module:voyager/main] Running prod benchmark...

**Comment by c0ldcertified** [comment]
i am seeing the same erros as above + this;

<h3 class="text-15 font-semibold mb-2">If you're the owner of this website:</h3>
          <p><span>It appears that the SSL configuration used is not compatible with Cloudflare. This could happen for a several reasons, including no shared cipher suites.</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200278659">Additional troubleshooting information here.</a></p>

**Comment by ricarper** [comment]
I'm getting this now
[2024-03-31T09:19:40Z ERROR module:voyager/main] Error: Failed to submit measurement (500): Internal Server Error
        at assertOkResponse (file:///home/node/.cache/filecoin-station-core/sources/voyager/voyager.js:30:17)
        at eventLoopTick (ext:core/01_core.js:178:11)
        at async bc.onReportLogs (file:///home/node/.cache/filecoin-station-core/sources/voyager/voyager.js:57:13) {
      statusCode: 500,
      serverMessage: "Internal Server Error"

**Comment by juliangruber** [comment]
> While running "docker logs filestation --follow" I see many internal server errors. See the attached log snippet [filestation.log](https://github.com/filecoin-station/core/files/14803221/filestation.log)

I don't find a single "internal server error" in this log file 🤔

**Comment by juliangruber** [comment]
> Same stituation here. [3/30/2024, 11:43:27 PM] INFO Voyager exited with code: 1 [3/30/2024, 11:43:27 PM] ERROR Voyager crashed with exit code 1 Reporting the poblem to Sentry for inspection by the Station team. [3/30/2024, 11:43:27 PM] INFO Spark exited via signal SIGTERM Zinnia closed all stdio with codes , 1

This can happen, and is currently expected. It's not an issue, as long as afterwards it resumes operation

**Comment by juliangruber** [comment]
> [2024-03-31T00:23:29Z ERROR module:voyager/main] Failed to fetch content { cause: "All attempts to fetch content have failed. Last error: Non OK response received: 410 Gone" } [2024-03-31T00:23:29Z INFO module:voyager/main] Prod benchmark successful! [2024-03-31T00:23:29Z ERROR module:voyager/main] Could not check if running on Saturn node { cause: `Unexpected token '<', "<!DOCTYPE "... is not valid JSON` } [2024-03-31T00:23:29Z INFO module:voyager/main] Running prod benchmark...

This is also nothing to worry about

**Comment by juliangruber** [comment]
> [2024-03-31T00:23:29Z ERROR module:voyager/main] Failed to fetch content { cause: "All attempts to fetch content have failed. Last error: Non OK response received: 410 Gone" } [2024-03-31T00:23:29Z INFO module:voyager/main] Prod benchmark successful! [2024-03-31T00:23:29Z ERROR module:voyager/main] Could not check if running on Saturn node { cause: `Unexpected token '<', "<!DOCTYPE "... is not valid JSON` } [2024-03-31T00:23:29Z INFO module:voyager/main] Running prod benchmark...

This is also nothing to worry about

**Comment by juliangruber** [comment]
> I'm getting this now [2024-03-31T09:19:40Z ERROR module:voyager/main] Error: Failed to submit measurement (500): Internal Server Error at assertOkResponse (file:///home/node/.cache/filecoin-station-core/sources/voyager/voyager.js:30:17) at eventLoopTick (ext:core/01_core.js:178:11) at async bc.onReportLogs (file:///home/node/.cache/filecoin-station-core/sources/voyager/voyager.js:57:13) { statusCode: 500, serverMessage: "Internal Server Error"

The API should be back up again.

I'm closing this issue, looks like these are all just transient errors

**Comment by ricarper** [comment]
The station freezes completely +- every 50 min. It only recovers by restarting the container every hour. Is this normal?

**Comment by ricarper** [comment]
I deleted and reinstalled it 2 days ago. Doesn't it update automatically?

**Comment by juliangruber** [comment]
Sorry I meant the version of Station Core

**Comment by ricarper** [comment]
> Sorry I meant the version of Station Core

Latest, install 2 days ago

**Comment by juliangruber** [comment]
The latest version is from today

**Comment by ricarper** [comment]
> The latest version is from today

Docker?

**Comment by ricarper** [comment]
> The latest version is from today

I just reinstalled it. I'll try it out. Wasn't it supposed to update itself?

**Comment by ricarper** [comment]
Same situation, 
[2024-04-02T20:16:34Z ERROR module:voyager/main] Error: Failed to submit measurement (500): Internal Server Error
        at assertOkResponse (file:///home/node/.cache/filecoin-station-core/sources/voyager/voyager.js:30:17)
        at eventLoopTick (ext:core/01_core.js:178:11)
        at async bc.onReportLogs (file:///home/node/.cache/filecoin-station-core/sources/voyager/voyager.js:57:13) {
      statusCode: 500,
      serverMessage: "Internal Server Error"

**Comment by juliangruber** [comment]
> > The latest version is from today
> 
> I just reinstalled it. I'll try it out. Wasn't it supposed to update itself?

Modules update themselves (SPARK & Voyager), but the thing that runs the modules (Station Core) needs to be updated manually. Or, you can use something like Watchtower to get automatic Docker updates



> Same situation, [2024-04-02T20:16:34Z ERROR module:voyager/main] Error: Failed to submit measurement (500): Internal Server Error at assertOkResponse (file:///home/node/.cache/filecoin-station-core/sources/voyager/voyager.js:30:17) at eventLoopTick (ext:core/01_core.js:178:11) at async bc.onReportLogs (file:///home/node/.cache/filecoin-station-core/sources/voyager/voyager.js:57:13) { statusCode: 500, serverMessage: "Internal Server Error"

This error is currently expected.

**Comment by ricarper** [comment]
I had removed watchtower because of conflicts with other containers that used its base. I'll reinstall it then.
Thanks for your support 
I'll give you feedback

**Comment by ricarper** [comment]
Just in case, I'll schedule a restart of the container every day at 01:30.
About checking the version of station core, can I see that on the command line?

**Comment by ricarper** [comment]
> How do you install Station Core?

Just like is mention, ghcr.io/filecoin-station/core

**Comment by ricarper** [comment]
You updated these 2 after we "talked", is the Watchtower going to make that change? 
![github_00](https://github.com/filecoin-station/core/assets/165522372/f267b58c-08ab-402e-a118-23c9db9d702a)

**Comment by ricarper** [comment]
Stuck again after 55 min running. This message is displayed every second. 


[2024-04-02T22:42:13Z INFO  module:voyager/main] Running on Saturn host, skipping benchmark
[2024-04-02T22:42:13Z ERROR module:voyager/main] Could not check if running on Saturn node {
      cause: "Failed to get public IP address (525): <!DOCTYPE html>\n" +
        '<!--[if lt IE 7]> <html class="no-js ie6 oldi'... 6862 more characters
    }
[2024-04-02T22:42:13Z INFO  module:voyager/main] Running on Saturn host, skipping benchmark

**Comment by juliangruber** [comment]
We are investigating SSL errors (`Failed to get public IP address (525)`) and deploying a workaround

**Comment by juliangruber** [comment]
> You updated these 2 after we "talked", is the Watchtower going to make that change?

Watchtower should pick up the new versions yes

**Comment by ricarper** [comment]
Is it useful to keep reporting here what I "discover" or not?

**Comment by juliangruber** [comment]
Best create new issues with specific errors 👍

**Comment by ricarper** [comment]
> Best create new issues with specific errors 👍

If I do not restart every hour the station freeze. At this moment are 17:56UTC and the station freeze at 
[4/3/2024, 2:48:13 PM] INFO  Voyager exited with code: 1
[4/3/2024, 2:48:13 PM] ERROR Voyager crashed with exit code 1
Reporting the poblem to Sentry for inspection by the Station team.
[4/3/2024, 2:48:13 PM] INFO  Spark exited via signal SIGTERM
