### ISSUE TITLE
Core - docker Failed to download voyager source

### ISSUE THREAD

**Issue by daisleyj** [filecoin-station/core#393]
When running core in docker the application continually returns the error

```shell
Failed to download voyager source. Retrying...
[voyager]  ⇣ downloading source files via https://bafkreignngdpq6g7qvai6phpau6jfjk7zvuih7rdf5zdga7jnq7n6zve3a.ipfs.w3s.link?format=car
[Error: ENOENT: no such file or directory, lstat '/home/node/.cache/filecoin-station-core/sources/voyager'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/node/.cache/filecoin-station-core/sources/voyager',
  attemptNumber: 8,
  retriesLeft: 3
```

This happens using the image built from the Dockerfile in the code repo and the image from ghcr.io/filecoin-station/core

**Comment by juliangruber** [comment]
These lstat errors should have been fixed since https://github.com/filecoin-station/core/releases/tag/v20.1.4, are you by chance running an outdated version?
