### ISSUE TITLE
Failed to get scheduled rewards: Error: server response 503

### ISSUE THREAD

**Issue by ricarper** [filecoin-station/core#396]
Failed to get scheduled rewards: Error: server response 503 Service Temporarily Unavailable (request={  }, response={  }, error=null, info={ "requestUrl": "https://api.node.glif.io/rpc/v1", "responseBody": "{\"message\":\"failure to get a peer from the ring-balancer\"}", "responseStatus": "503 Service Temporarily Unavailable" }, code=SERVER_ERROR, version=6.11.1)
    at makeError (file:///usr/src/app/node_modules/ethers/lib.esm/utils/errors.js:124:21)
    at assert (file:///usr/src/app/node_modules/ethers/lib.esm/utils/errors.js:143:15)
    at FetchResponse.assertOk (file:///usr/src/app/node_modules/ethers/lib.esm/utils/fetch.js:833:9)
    at JsonRpcProvider._send (file:///usr/src/app/node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:880:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///usr/src/app/node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:277:40
{
  "totalJobsCompleted": 72989,
  "rewardsScheduledForAddress": "0.0"

**Comment by ricarper** [comment]
[2024-04-04T21:58:21Z ERROR module:voyager/main] Failed to fetch content {
      cause: "All attempts to fetch content have failed. Last error: file does not exist"
    }

**Comment by ricarper** [comment]
[2024-04-04T22:57:00Z INFO  module:voyager/main] Prod benchmark successful!
Failed to get scheduled rewards: Error: getaddrinfo EAI_AGAIN api.node.glif.io

**Comment by c0ldcertified** [comment]
[2024-04-05T00:16:40Z ERROR module:voyager/main] Failed to fetch content {
      cause: "All attempts to fetch content have failed. Last error: get QmTjrJz4wH7agWixbEza6KZXZT1YZ39Tajq6Y14Nh"... 70 more characters
    }

**Comment by juliangruber** [comment]
> [2024-04-04T21:58:21Z ERROR module:voyager/main] Failed to fetch content { cause: "All attempts to fetch content have failed. Last error: file does not exist" }

Errors with "Failed to fetch content" can be ignored. Please also don't post multiple different errors in the same issue.

> [2024-04-04T22:57:00Z INFO module:voyager/main] Prod benchmark successful!
Failed to get scheduled rewards: Error: getaddrinfo EAI_AGAIN api.node.glif.io

It looks like you were unable to reach api.node.glif.io. Has your station node recovered?

**Comment by ricarper** [comment]
> > [2024-04-04T21:58:21Z ERROR module:voyager/main] Failed to fetch content { cause: "All attempts to fetch content have failed. Last error: file does not exist" }
> 
> Errors with "Failed to fetch content" can be ignored. Please also don't post multiple different errors in the same issue.
> 
> > [2024-04-04T22:57:00Z INFO module:voyager/main] Prod benchmark successful!
> > Failed to get scheduled rewards: Error: getaddrinfo EAI_AGAIN api.node.glif.io
> 
> It looks like you were unable to reach api.node.glif.io. Has your station node recovered?

Recovered after restart
