### ISSUE TITLE
Docker instance crashes trying to create directory in incorrect spot

### ISSUE THREAD

**Issue by zipiju** [filecoin-station/core#435]
Trying to run Core in a container.
After the start, the :latest (20.2.1) instance stops with the following in the logs, where /bin/bash isn't a directory:

```
Usage: station.js [options]

Options:
  -j, --json          Output JSON                                      [boolean]
      --experimental  Also run experimental modules                    [boolean]
  -v, --version       Show version number                              [boolean]
  -h, --help          Show help                                        [boolean]

[Error: ENOTDIR: not a directory, mkdir '/bin/bash/.local/state/filecoin-station-core/secrets'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'mkdir',
  path: '/bin/bash/.local/state/filecoin-station-core/secrets'
}
```

When I pull 20.1.8 and cut Internet access, the instance runs.
As soon as access is enabled, it again stops with the following, most likely after pulling an update:

```
Usage: station.js [options]

Options:
  -j, --json          Output JSON                                      [boolean]
      --experimental  Also run experimental modules                    [boolean]
  -v, --version       Show version number                              [boolean]
  -h, --help          Show help                                        [boolean]

[Error: ENOTDIR: not a directory, mkdir '/bin/bash/.cache/filecoin-station-core/modules/zinnia'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'mkdir',
  path: '/bin/bash/.cache/filecoin-station-core/modules/zinnia'
}
```

```
root@frankfurt:/usr/src/app# ls -lah /bin/bash
-rwxr-xr-x 1 root root 1.3M Apr 23  2023 /bin/bash
```

**Comment by zipiju** [comment]
This issue can be fixed by passing these variables to the container:
CACHE_ROOT=/usr/src/app/.cache
STATE_ROOT=/usr/src/app/.local/state

**Comment by bajtos** [comment]
I think this issue was introduced by #424.

However, we are calling `mkdir -p` to create any missing directories, I am surprised you are seeing `ENOTDIR` errors.

https://github.com/filecoin-station/core/blob/4a177aea027de7086c74686070040f72ecb60993/lib/station-id.js#L15

Looking at the path "/bin/bash/.local/state/filecoin-station-core/secrets", I suspect the HOME environment variable is not set inside the Docker container or is set to a wrong value (`HOME=/bin/bash`).

It would be great to understand why we have not encountered this error when running the Docker image in our CI (GitHub Actions) and when deployed to Fly.io.

**Comment by bajtos** [comment]
I propose to add `HOME=/usr/src/app` after setting the WORKDIR in the Dockerfile:

https://github.com/filecoin-station/core/blob/4a177aea027de7086c74686070040f72ecb60993/Dockerfile#L4

Thoughts?

**Comment by juliangruber** [comment]
I assume mkdirp doesn't work if you want to create a directory inside a binary (`/bin/bash`). I missed that when first reading the issue. I wonder why HOME behaves differently for different docker installations 🤔 It looks like a bug for this version of Docker to set HOME to /bin/bash

**Comment by zipiju** [comment]
Hard to tell if it is actually a Docker. This is running on Mikrotik CHR, so it is possible they are using something else and/or the user it is running as has the home directory set incorrectly as mentioned by Miro.

**Comment by juliangruber** [comment]
got it, then I believe this is an issue with that platform, and operators using that platform can fix it by setting $HOME correctly themselves. I believe they're not using Docker, so us updating our Dockerfile won't help them.
