### ISSUE TITLE
Failed to validate FIL_WALLET_ADDRESS address

### ISSUE THREAD

**Issue by ricarper** [filecoin-station/core#449]
All my gateways have been in this state indefinitely today (12 hours ago)

Failed to validate FIL_WALLET_ADDRESS address
Loaded Station ID:

What can we do to resolve the blockage? 

@juliangruber can you help?

**Comment by ricarper** [comment]
I tried deleting the container and reinstalling but I got this and it was blocked 

*****************************************************************************************
  The private key of the identity of your Station instance will be stored in plaintext.
  We strongly recommend you to configure PASSPHRASE environment variable to enable
  Station to encrypt the private key stored on the filesystem.
*****************************************************************************************

(node:1) ExperimentalWarning: The Ed25519 Web Crypto API algorithm is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Generated a new Station ID:

**Comment by slick202** [comment]
maybe FIL Wallet validation url is offline or something

station-wallet-screening.fly.dev seems to be causing the issue somehow not validating the FIL WALLET ADDRESS

maybe the host is down?

**Comment by ricarper** [comment]
> maybe FIL Wallet validation url is offline or something
> 
> station-wallet-screening.fly.dev seems to be causing the issue somehow not validating the FIL WALLET ADDRESS
> 
> seems like host is down...

All the wallets, or just mine?
It happened after implementing the package-lock.json update today

**Comment by slick202** [comment]
I am having the same issues as yourself with filecoin-station/core 

not sure who can help us??

**Comment by ricarper** [comment]
> I am having the same issues as yourself with filecoin-station/core
> 
> not sure who can help us??

I tried reinstalling the container and it didn't work. I was going to try changing the associated wallet, but if you're having the same problem, it's not our problem.

**Comment by bajtos** [comment]
I think there was a problem with the deployment of our wallet screening service. I believe I have fixed the problem few minutes ago.

Sorry for the downtime!

**Comment by bajtos** [comment]
> All the wallets, or just mine?

The problem affected all wallets.

**Comment by hongster** [comment]
@bajtos It is still down at this moment (Sun 29 Jun 2025 05:50:08 PM +08). Is it possible to replace it with another more reliable service?

**Comment by juliangruber** [comment]
@hongster please see https://x.com/FilecoinCDN/status/1932472254245298504
