### ISSUE TITLE
Please check if the balance in the contract is insufficient. 

### ISSUE THREAD

**Issue by csmasterpath2023** [filecoin-station/core#455]
According to the last transfer of 500 FIL, it has been 18 days until today. Based on a total of 1000 per month, the daily expenditure is about 33.3. Since the last transfer, the contract expenditure has exceeded 540

**Comment by juliangruber** [comment]
The balance is sufficient and not negatively impacting payouts. I have just topped it up though, as it was getting a bit low.

**Comment by juliangruber** [comment]
With [nodejs](https://nodejs.org) installed, you can check the contract balance yourself:

```bash
$ npx meridian available-balance --address 0x8460766Edc62B525fc1FA4D628FC79229dC73031
34.418694628501832271 FIL
```

**Comment by juliangruber** [comment]
After topping up:

```
534.418694628501832271 FIL
```
