### ISSUE TITLE
Frozen Rewards all gateways

### ISSUE THREAD

**Issue by ricarper** [filecoin-station/core#485]
In 5 hours it will be 24 hours since the rewards stopped at all gateways. There is no error and the rewards are frozen. Is everything all right?

**Comment by ricarper** [comment]
The jobs still count, it's the rewards that are frozen.

**Comment by ricarper** [comment]
Restarting the container solved the problem. The problem is that these blockages for no apparent reason and without errors are very constant.

**Comment by bajtos** [comment]
We are relying on the public RPC API service provided by Glif at https://api.node.glif.io, and there have been partial outages recently. 

> The problem is that these blockages for no apparent reason and without errors are very constant.

Would it help if Station Core and/or Station Desktop reported an activity log when it cannot update the scheduled rewards? Maybe we can implement a similar mechanism as we have in Spark & Voyager where the module can be online or offline.

@juliangruber WDYT?

**Comment by juliangruber** [comment]
@bajtos are you sure this is because of the Glif unavailability?

**Comment by ricarper** [comment]
It stopped again 10 hours ago. Restarting the container doesn't solve it. Work continues and no errors are generated. All gateways.

**Comment by ricarper** [comment]
It's frozzen again 5 hours. Restarting the container doesn't solve it. Work continues and no errors are generated. All gateways.

**Comment by juliangruber** [comment]
Can you please check again?

**Comment by ricarper** [comment]
> Can you please check again?

Two hours before your comment it was out of rewards and remained that way for another two hours. Then it seems to have recovered.
There have been a lot of failures in the rewards. I don't know what's going on.

**Comment by juliangruber** [comment]
I'm glad it has recovered! We're working hard to ensure steady operation. Please re-open if rewards shuold pause for you again.
