### ISSUE TITLE
DOCKER - Scheduled Rewards always showing 0.0

### ISSUE THREAD

**Issue by openhost-marcb** [filecoin-station/core#509]
**I've been running a few dockers of filcoin for a little and recently encountered 1 on my dockers always reporting 0.0 balance.**

**I tried to recreate it and it still seems to produce the same issue. I'm wondering if the wallet for some reason is causing the problem.**

------------------------
[2024-06-13T14:41:59Z INFO  module:spark/main] Calling Filecoin JSON-RPC to get PeerId of miner f02934869
[2024-06-13T14:42:00Z INFO  module:spark/main] Found peer id: 12D3KooWGeRLVdK2VckCJkrWx2wkvKTjcFLvJmvgD2cBdqBiUtwf
[2024-06-13T14:42:00Z INFO  module:spark/main] Querying IPNI to find retrieval providers for bafybeihxyt2bndaew7vbzgnfiu5qvfvbtdrf2grlhhiek2etbod62uzvsa
[2024-06-13T14:42:00Z ERROR module:spark/main] IPNI query failed, HTTP response: 404
[2024-06-13T14:42:00Z INFO  module:spark/main] Submitting measurement...
[2024-06-13T14:42:00Z INFO  module:spark/main] {
      sparkVersion: "1.12.1",
      zinniaVersion: "0.19.1",
      cid: "bafybeihxyt2bndaew7vbzgnfiu5qvfvbtdrf2grlhhiek2etbod62uzvsa",
      minerId: "f02934869",
      timeout: false,
      startAt: 2024-06-13T14:41:59.679Z,
      firstByteAt: null,
      endAt: null,
      carTooLarge: false,
      byteLength: 0,
      carChecksum: null,
      statusCode: null,
      providerId: "12D3KooWGeRLVdK2VckCJkrWx2wkvKTjcFLvJmvgD2cBdqBiUtwf",
      indexerResult: "ERROR_404",
      participantAddress: "0x6b020dB89390e7c8aDC5723b65745333F24F2931",
      stationId: "302a300506032b6570032100396bb20e4ab22628fa42157134bff4b1c6a4f9bd3070a3cfa98a0e81c4f32f83"
    }
[2024-06-13T14:42:00Z INFO  module:spark/main] Measurement submitted (id: 5539898269)
{
  "totalJobsCompleted": 1206,
  "rewardsScheduledForAddress": "0.0"

**Comment by juliangruber** [comment]
Can you please DM the wallet address on Filecoin Slack -> #station, or send via email?

**Comment by openhost-marcb** [comment]
Thanks for the email back,

 

0x6b020dB89390e7c8aDC5723b65745333F24F2931

Or 
f410fnmba3oetsdt4rlofoi5wk5ctgpze6kjribfpnia

**Comment by juliangruber** [comment]
Scheduled rewards for this address are indeed 0. Could it be that you're running multiple Station Core instances on the same IP address or IPv4 subnet?

**Comment by openhost-marcb** [comment]
is there a restriction on the local network or do you mean public ip address?

**Comment by juliangruber** [comment]
The network per round only rewards one node in every IPv4 subnet, to make it hard for bad parties to manipulate the results

**Comment by openhost-marcb** [comment]
Yes for sure. Another question is as well I’m looking at creating a script to transact on the filcoin network via glif.io but ran into a snag. Always getting invalid request after ensuring all my transaction details are encoded. I suspect the issue is with the signature base64 encoding but can’t seem to find and information on what is the correct usage.

 

The docs indicate base64 but when I look at the sample transactions from the docs my string seems way too long.

 

While trying to adjust I get this error as well

{"jsonrpc":"2.0","error":{"code":-32700,"message":"unmarshaling params for 'Filecoin.MpoolPush' (param: **types.SignedMessage): failed to parse big string: '\"0.1\"'"},"id":1}

 

Is there any reference documents you can direct me that might help resolve my issue.

 

Thank you again

**Comment by juliangruber** [comment]
can you please open a new issue with this?
