### ISSUE TITLE
Frozen nodes

### ISSUE THREAD

**Issue by ricarper** [filecoin-station/core#543]
Almost 12 hours with all nodes blocked with no rewards and jobs increasing.
No error appears.

**Comment by ricarper** [comment]
Nodes still blocked with no rewards and jobs increasing.
Restart doesn't solve the problem and no error appears.

**Comment by ricarper** [comment]
indexerResult changed from "ERROR_404" to "NO_VALID_ADVERTISEMENT"

**Comment by ricarper** [comment]
It only started working again for an hour (few hours ago) and stopped again.
indexerResult changed again from "NO_VALID_ADVERTISEMENT" to "ERROR_404".

**Comment by juliangruber** [comment]
I'm looking into this

> indexerResult changed from "ERROR_404" to "NO_VALID_ADVERTISEMENT"

This is an ok result and has nothing to do with stuck rewards

**Comment by juliangruber** [comment]
There was an error with request batching: Glif JSON-RPC APIs were rejecting messages because the batches consisted of more than 10 messages. This has now been fixed, and rewards should be resumed.
