### ISSUE TITLE
1 wallet for machine?

### ISSUE THREAD

**Issue by AlexBion** [filecoin-station/core#545]
Sorry for writing here, but I couldn't find a FAQ section. If I wanted to install Docker Core on 2 Linux machines with different IPs, can I use the same destination wallet?

**Comment by ricarper** [comment]
> Sorry for writing here, but I couldn't find a FAQ section. If I wanted to install Docker Core on 2 Linux machines with different IPs, can I use the same destination wallet?

Yes you can

**Comment by bajtos** [comment]
The IP address that our HTTP server sees when it receives the request from your Station instance. In fact, we are only looking at the first 3 bytes of the IPv4 address and ignoring the fourth byte. If you have two station instances running in the same IPv4 /24 subnet, then the rewards will be split between them.
