### ISSUE TITLE
Rewards drop to 0.000000000000000001

### ISSUE THREAD

**Issue by ricarper** [filecoin-station/core#558]
From 3 hours ago until now, the combined rewards of all the nodes are at 0.000000000000000001.
I noticed that when the indexerResult changes from error404 to NO_VALID_ADVERTISEMENT, the rewards go to 0.

**Comment by bajtos** [comment]
> From 3 hours ago until now, the combined rewards of all the nodes are at 0.000000000000000001. 

I noticed there was an increase in the number of nodes sharing the same IPv4 /24 subnet. The protocol splits the reward in such case. If there are 10 nodes in the same subnet, then each node earns approx. 1/10th of what it would earn if it were the only node in the subnet.

Could that explain what you are seeing?

> I noticed that when the indexerResult changes from error404 to NO_VALID_ADVERTISEMENT, the rewards go to 0.

That's almost certainly not the cause. The algorithm calculating rewards does not look at the retrieval results.

**Comment by juliangruber** [comment]
The contract balance ran out, I'm fixing right now

**Comment by juliangruber** [comment]
Everything should be back to normal
