### ISSUE TITLE
Station Core unable to start after an update

### ISSUE THREAD

**Issue by zipiju** [filecoin-station/core#565]
Containerised version unable to start after an update today:
```
import { addOpenTelemetryInstrumentation, getPropagationContextFromSpan, generateSpanContextForPropagationContext } from '@sentry/opentelemetry';
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '@sentry/opentelemetry' does not provide an export named 'generateSpanContextForPropagationContext'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.16.0
```

**Comment by bajtos** [comment]
@zipiju thank you for the bug report. I am afraid I cannot reproduce this problem.

Here is what I tried:

```
docker run --rm -it --name=station --env FIL_WALLET_ADDRESS=0x000000000000000000000000000000000000dead ghcr.io/filecoin-station/core:21.2.0
```

On my machine, Station Core launched and started performing Spark retrieval checks.

What is the version of the Docker image you are running? How exactly do you start the container?

**Comment by zipiju** [comment]
Hello and thank you for taking a look.
It was actually some issue where the old source was not fully (or at all) deleted from the drive, probably causing errors when some older libs were present and the application expected new. Not sure what is running containers on this platform, but it isn't Docker probably. Normally, when removing the containers, the sources are removed as well, but this time this wasn't the case - probably related to the software version this is currently running.
Removing the container, then manually deleting the container sources directory and installing the container again fixed the issue.
