### ISSUE TITLE
Dockerfile lint: Legacy key/value format with whitespace separator should not be used

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/core#586]
<img width="648" alt="Screenshot 2024-08-29 at 17 57 46" src="https://github.com/user-attachments/assets/1932ea64-3331-4823-89be-9d9e9b816dca">

**Comment by juliangruber** [comment]
Fixed in https://github.com/filecoin-station/core/commit/e895f0be37f9fe8c0967b9d4048cd20c260e8419
