### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/home/node/.local/state/filecoin-station-core'

### ISSUE THREAD

**Issue by renarios** [filecoin-station/core#629]
While trying to run a docker with:

>  docker run --name station --detach --env FIL_WALLET_ADDRESS=XXXXXXXXXXXXX2 -v ./state:/home/node/.local/state/ ghcr.io/filecoin-station/core

 I exits within a second.

Here is the error:
> docker logs -f station
> Usage: station.js [options]
> 
> Options:
>   -j, --json                      Output JSON                          [boolean]
>       --experimental              Also run experimental modules        [boolean]
>       --recreateStationIdOnError  Recreate Station ID if it is corrupted
>                                                                        [boolean]
>   -v, --version                   Show version number                  [boolean]
>   -h, --help                      Show help                            [boolean]
> 
> Error: EACCES: permission denied, mkdir '/home/node/.local/state/filecoin-station-core'
>     at async Object.mkdir (node:internal/fs/promises:858:10)
>     at async getStationId (file:///usr/src/app/lib/station-id.js:17:3)
>     at async station (file:///usr/src/app/commands/station.js:49:19) {
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'mkdir',
>   path: '/home/node/.local/state/filecoin-station-core'
> }

Removing the docker and running it again doesn't help. What can I do?

**Comment by bajtos** [comment]
Hi @renarios, thank you for reporting this issue. Please read the discussion at https://github.com/filecoin-station/core/issues/456; it offers different options to troubleshoot and fix this problem.
