### ISSUE TITLE
Unable to access ghcr.io, requesting Docker Hub mirror

### ISSUE THREAD

**Issue by yeahwong** [filecoin-station/core#87]
I am currently unable to access ghcr.io due to network restrictions, which is preventing me from using the necessary images for my tasks. As a workaround, I kindly request that a Docker Hub mirror be made available to allow for uninterrupted use of the images required. Thank you for your prompt attention to this matter.

**Comment by juliangruber** [comment]
We recently made a change to our ghcr.io image, can you please try again?

**Comment by yeahwong** [comment]
Thank you. That's great, I have successfully installed it.

**Comment by juliangruber** [comment]
Great! Turns out it wasn't network restrictions at all, but rather an issue with our GitHub configuration

**Comment by yeahwong** [comment]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/5824590/235367668-39e6b6a7-edea-47b8-a0f8-646e09858e94.png">

@juliangruber Some errors have occurred.

**Comment by yeahwong** [comment]
Because of the existence of the Great Firewall, there is a bad network environment. When I was setting proxy parameters for containers using Synology Docker, it did not work. Can you create support for an internal proxy server of HTTP or SOCKS?

**Comment by juliangruber** [comment]
Can you please open a new issue for proxy support? 🙏
