### ISSUE TITLE
docker image builds in CI failing?

### ISSUE THREAD

**Issue by mroth** [filecoin-station/core#90]
Docker image builds appear to have been failing since v5.0:
https://github.com/filecoin-station/core/actions/workflows/docker.yml

From looking at the logs, it appears that the `npm ci` RUN command is failing as it depends on the `scripts/post-install.js` file which is not copied  prior to this step.

(A fix may be to copy the scripts directory prior to this step in the Dockerfile, but I am opening as an issue as I'm not sure if that dependency is desirable or unintended.)

**Comment by bajtos** [comment]
I this the problem was introduced by #83

**Comment by juliangruber** [comment]
https://github.com/filecoin-station/core/releases/tag/v5.2.1

https://github.com/filecoin-station/core/pkgs/container/core
